var annotated_dup =
[
    [ "ArrayList", "structArrayList.html", null ],
    [ "Atlas", "structAtlas.html", null ],
    [ "AudioConfigStruct", "structAudioConfigStruct.html", null ],
    [ "AudioEmitterStruct", "structAudioEmitterStruct.html", null ],
    [ "AudioListenerStruct", "structAudioListenerStruct.html", null ],
    [ "Camera", "structCamera.html", null ],
    [ "Chunk", "structChunk.html", null ],
    [ "FEUR_Test", "structFEUR__Test.html", null ],
    [ "FEUR_Test_Group", "structFEUR__Test__Group.html", null ],
    [ "FEUR_Tester", "structFEUR__Tester.html", null ],
    [ "Geometry", "structGeometry.html", null ],
    [ "Image", "structImage.html", null ],
    [ "ImageArray", "structImageArray.html", null ],
    [ "Keyboard", "structKeyboard.html", null ],
    [ "Mat4", "structMat4.html", null ],
    [ "Mesh", "structMesh.html", null ],
    [ "Renderer", "structRenderer.html", null ],
    [ "Shader", "structShader.html", null ],
    [ "ShaderProgram", "structShaderProgram.html", null ],
    [ "Texture", "structTexture.html", null ],
    [ "TextureArray", "structTextureArray.html", null ],
    [ "TextureCoord", "structTextureCoord.html", null ],
    [ "Transform", "structTransform.html", null ],
    [ "Vec2", "structVec2.html", null ],
    [ "Vec3", "structVec3.html", null ],
    [ "Vec3i", "structVec3i.html", null ],
    [ "Vec4", "structVec4.html", null ],
    [ "Vertex", "structVertex.html", null ],
    [ "VertexAttribute", "structVertexAttribute.html", null ],
    [ "VertexBlock", "structVertexBlock.html", null ],
    [ "VertexLayout", "structVertexLayout.html", null ],
    [ "VertexUV", "structVertexUV.html", null ],
    [ "Window", "structWindow.html", null ]
];