var annotated_dup =
[
    [ "ArrayList", "structArrayList.html", "structArrayList" ],
    [ "Atlas", "structAtlas.html", "structAtlas" ],
    [ "Camera", "structCamera.html", "structCamera" ],
    [ "Chunk", "structChunk.html", "structChunk" ],
    [ "FEUR_Test", "structFEUR__Test.html", "structFEUR__Test" ],
    [ "FEUR_Test_Group", "structFEUR__Test__Group.html", "structFEUR__Test__Group" ],
    [ "FEUR_Tester", "structFEUR__Tester.html", "structFEUR__Tester" ],
    [ "Geometry", "structGeometry.html", "structGeometry" ],
    [ "Image", "structImage.html", "structImage" ],
    [ "ImageArray", "structImageArray.html", "structImageArray" ],
    [ "Keyboard", "structKeyboard.html", "structKeyboard" ],
    [ "Mat4", "structMat4.html", "structMat4" ],
    [ "Mesh", "structMesh.html", "structMesh" ],
    [ "Renderer", "structRenderer.html", "structRenderer" ],
    [ "Shader", "structShader.html", "structShader" ],
    [ "ShaderProgram", "structShaderProgram.html", "structShaderProgram" ],
    [ "Texture", "structTexture.html", "structTexture" ],
    [ "TextureArray", "structTextureArray.html", "structTextureArray" ],
    [ "TextureCoord", "structTextureCoord.html", "structTextureCoord" ],
    [ "Transform", "structTransform.html", "structTransform" ],
    [ "Vec2", "structVec2.html", "structVec2" ],
    [ "Vec3", "structVec3.html", "structVec3" ],
    [ "Vec3i", "structVec3i.html", "structVec3i" ],
    [ "Vec4", "structVec4.html", "structVec4" ],
    [ "Vertex", "structVertex.html", "structVertex" ],
    [ "VertexAttribute", "structVertexAttribute.html", "structVertexAttribute" ],
    [ "VertexBlock", "structVertexBlock.html", "structVertexBlock" ],
    [ "VertexLayout", "structVertexLayout.html", "structVertexLayout" ],
    [ "VertexUV", "structVertexUV.html", "structVertexUV" ],
    [ "Window", "structWindow.html", "structWindow" ]
];