#ifndef GEOMETRY_DATA_H
#define GEOMETRY_DATA_H

#include "vertex.h"

#define CUBE_VERTICES_AMOUNT 8
#define CUBE_INDICES_AMOUNT 36

extern const Vertex CUBE_VERTICES[CUBE_VERTICES_AMOUNT];
extern const unsigned int CUBE_INDICES[CUBE_INDICES_AMOUNT];

#define CUBE_UV_VERTICES_AMOUNT 24
#define CUBE_UV_INDICES_AMOUNT 36

extern const VertexUV CUBE_UV_VERTICES[CUBE_UV_VERTICES_AMOUNT];
extern const unsigned int CUBE_UV_INDICES[CUBE_UV_INDICES_AMOUNT];


#define BLOCK_VERTICES_AMOUNT 24
#define BLOCK_INDICES_AMOUNT 36

extern const VertexBlock BLOCK_VERTICES[BLOCK_VERTICES_AMOUNT];
extern const unsigned int BLOCK_INDICES[BLOCK_INDICES_AMOUNT];

#define BLOCK_FACE_VERTICES_AMOUNT 4
#define BLOCK_FACE_INDICES_AMOUNT 6

extern const VertexBlock BLOCK_FACE_FRONT_VERTICES[BLOCK_FACE_VERTICES_AMOUNT];
extern const VertexBlock BLOCK_FACE_BACK_VERTICES[BLOCK_FACE_VERTICES_AMOUNT];
extern const VertexBlock BLOCK_FACE_TOP_VERTICES[BLOCK_FACE_VERTICES_AMOUNT];
extern const VertexBlock BLOCK_FACE_BOT_VERTICES[BLOCK_FACE_VERTICES_AMOUNT];
extern const VertexBlock BLOCK_FACE_LEFT_VERTICES[BLOCK_FACE_VERTICES_AMOUNT];
extern const VertexBlock BLOCK_FACE_RIGHT_VERTICES[BLOCK_FACE_VERTICES_AMOUNT];
extern const unsigned int BLOCK_FACE_INDICES[BLOCK_FACE_INDICES_AMOUNT];

void geometry_data_get_block_face_vertices(BlockFace face, VertexBlock* out_vertices_buffer);

#endif // GEOMETRY_DATA_H
